---
# Welcome to RPComanies config !

# Current countries: Amazonia, Australia, China, Egypt, France, Peru, Russia, USA.

# This is the world where the plugin should affect (add the level name here BEFORE 
# generating so the countries will generate proprely)
RPLevel: world

# Choose with how much money does the companies starts with & costs:
DefaultCompanyPrice: 5000
...